# -*- coding: utf-8 -*-
"""
GitHub Hosts Updater - Windows 应用
数据源: fliu2476/gh-hosts + GitHub520 + fetch-github-hosts
运行后自动多源下载最新 hosts、对候选 IP 做 TCP 测速优选、
更新本地 hosts 文件并刷新 DNS 缓存。
"""

import os
import re
import sys
import time
import socket
import ctypes
import locale
import subprocess
import urllib.request
import urllib.error
import datetime
import threading
import tkinter as tk
from tkinter import scrolledtext, messagebox
from concurrent.futures import ThreadPoolExecutor

# ============ 配置 ============
HOSTS_URLS = [
    # GitHub520（专属 CDN，无需访问 GitHub 即可下载，服务端每小时更新）
    "https://raw.hellogithub.com/hosts",
    # fetch-github-hosts（独立 CDN）
    "https://hosts.gitcdn.top/hosts.txt",
    # fliu2476/gh-hosts 三源
    "https://ghfast.top/https://raw.githubusercontent.com/fliu2476/gh-hosts/main/hosts",
    "https://raw.githubusercontent.com/fliu2476/gh-hosts/main/hosts",
    "https://gitee.com/fliu2476/github-hosts/raw/main/hosts",
]
HOSTS_PATH = r"C:\Windows\System32\drivers\etc\hosts"
# 本程序写入 hosts 时使用的统一标记段
SECTION_START = "# GitHub Hosts Updater start"
SECTION_END = "# GitHub Hosts Updater end"
# 旧版本（fliu2476/gh-hosts）使用的标记段，更新时需要清理
LEGACY_SECTION_START = "# Generated by Github Hosts start"
LEGACY_SECTION_END = "# Generated by Github Hosts end"
BACKUP_DIR = os.path.join(os.path.expanduser("~"), ".gh_hosts_backup")
LOG_DIR = os.path.join(os.path.expanduser("~"), ".gh_hosts_logs")
REQUEST_TIMEOUT = 15  # 秒
SPEED_TEST_PORT = 443
SPEED_TEST_TIMEOUT = 3.0  # 单次 TCP 连接超时（秒）
SPEED_TEST_ATTEMPTS = 2  # 每个 IP 测速次数，取平均
SPEED_TEST_WORKERS = 16  # 测速并发线程数
IPV4_PATTERN = re.compile(r"^\d{1,3}(\.\d{1,3}){3}$")
# 获取系统默认编码
SYSTEM_ENCODING = locale.getpreferredencoding(False) or "gbk"
# ==============================


def write_log_to_file(msg):
    """将日志写入文件（线程安全）"""
    try:
        os.makedirs(LOG_DIR, exist_ok=True)
        today = datetime.date.today().strftime("%Y%m%d")
        log_file = os.path.join(LOG_DIR, f"gh_hosts_{today}.log")
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        line = f"[{timestamp}] {msg}\n"
        with open(log_file, "a", encoding="utf-8") as f:
            f.write(line)
    except Exception:
        pass


def is_admin():
    """检查是否具有管理员权限"""
    try:
        return ctypes.windll.shell32.IsUserAnAdmin()
    except Exception:
        return False


def run_as_admin():
    """以管理员权限重新启动当前程序"""
    try:
        params = " ".join([f'"{arg}"' for arg in sys.argv])
        ctypes.windll.shell32.ShellExecuteW(
            None, "runas", sys.executable, params, None, 1
        )
    except Exception as e:
        raise RuntimeError(f"无法请求管理员权限: {e}")


def _fetch_url(url):
    """下载单个 URL，返回文本内容（失败返回 None）"""
    try:
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                              "AppleWebKit/537.36 (KHTML, like Gecko) "
                              "Chrome/120.0.0.0 Safari/537.36"
            },
        )
        with urllib.request.urlopen(req, timeout=REQUEST_TIMEOUT) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except Exception:
        return None


def download_all_sources(logger):
    """并发从所有数据源下载 hosts，返回成功源的内容列表（按 HOSTS_URLS 优先级排序）"""
    logger("---------- 多源并发下载 ----------")
    contents = []
    with ThreadPoolExecutor(max_workers=len(HOSTS_URLS)) as pool:
        results = list(pool.map(_fetch_url, HOSTS_URLS))
    for url, content in zip(HOSTS_URLS, results):
        if content and content.strip():
            logger(f"✓ {url}（{len(content)} 字符）")
            contents.append(content)
        else:
            logger(f"✗ {url} 下载失败")
    if contents:
        logger(f"共 {len(contents)}/{len(HOSTS_URLS)} 个数据源可用")
    return contents


def parse_hosts_entries(contents, logger):
    """解析所有源内容，归并每个域名的候选 IP 列表（去重、按源优先级排序）"""
    candidates = {}  # domain -> [ip, ...]
    for content in contents:
        for line in content.splitlines():
            # hosts 格式中 # 之后均为注释
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) < 2 or not IPV4_PATTERN.match(parts[0]):
                continue
            ip = parts[0]
            for domain in parts[1:]:
                if "." not in domain:
                    continue  # 跳过非域名 token
                ip_list = candidates.setdefault(domain, [])
                if ip not in ip_list:
                    ip_list.append(ip)
    if candidates:
        total_ips = sum(len(v) for v in candidates.values())
        logger(f"解析完成: {len(candidates)} 个域名, {total_ips} 个域名-IP 条目")
    return candidates


def speed_test_ips(ips, logger):
    """并发对候选 IP 做 TCP 连接测速，返回 {ip: 平均延迟ms}（不可达的 IP 不在结果中）"""

    def test_one(ip):
        latencies = []
        for _ in range(SPEED_TEST_ATTEMPTS):
            t0 = time.perf_counter()
            try:
                with socket.create_connection(
                    (ip, SPEED_TEST_PORT), timeout=SPEED_TEST_TIMEOUT
                ):
                    latencies.append((time.perf_counter() - t0) * 1000)
            except Exception:
                return None
        return sum(latencies) / len(latencies)

    logger(f"开始 IP 优选测速: {len(ips)} 个候选 IP, "
           f"端口 {SPEED_TEST_PORT}, 每个测 {SPEED_TEST_ATTEMPTS} 次取平均...")
    results = {}
    with ThreadPoolExecutor(max_workers=SPEED_TEST_WORKERS) as pool:
        for ip, ms in zip(ips, pool.map(test_one, ips)):
            if ms is not None:
                results[ip] = ms
    logger(f"测速完成: {len(results)}/{len(ips)} 个 IP 可用")
    return results


def select_best_ips(candidates, speed_enabled, logger):
    """为每个域名选出最优 IP，返回 [(ip, domain), ...]

    测速启用时选延迟最低的候选 IP；某域名所有候选均不可达时，
    回退到最高优先级源给出的 IP。
    """
    # 汇总所有唯一 IP（不同域名常共用同一批 IP，只测一次）
    all_ips = []
    for ips in candidates.values():
        for ip in ips:
            if ip not in all_ips:
                all_ips.append(ip)

    latency = speed_test_ips(all_ips, logger) if (speed_enabled and all_ips) else {}
    if not speed_enabled:
        logger("IP 优选测速已禁用，直接使用最高优先级源的数据")

    entries = []
    for domain, ips in candidates.items():
        best = None
        if latency:
            available = [(latency[ip], ip) for ip in ips if ip in latency]
            if available:
                best = min(available)[1]
        if best is None:
            best = ips[0]  # 回退：最高优先级源的 IP
            logger(f"  {domain} -> {best}（回退默认）")
        else:
            logger(f"  {domain} -> {best}（{latency[best]:.0f}ms）")
        entries.append((best, domain))
    return entries


def build_section(entries):
    """根据优选结果生成本程序的 hosts 标记段"""
    lines = [SECTION_START]
    for ip, domain in entries:
        lines.append(f"{ip} {domain}")
    lines.append(SECTION_END)
    return "\n".join(lines)


def backup_hosts(logger):
    """备份当前 hosts 文件"""
    os.makedirs(BACKUP_DIR, exist_ok=True)
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = os.path.join(BACKUP_DIR, f"hosts_{timestamp}.bak")
    try:
        with open(HOSTS_PATH, "r", encoding="utf-8", errors="ignore") as f:
            original = f.read()
        with open(backup_path, "w", encoding="utf-8") as f:
            f.write(original)
        logger(f"已备份原 hosts 文件到: {backup_path}")
        return original
    except Exception as e:
        logger(f"备份失败: {e}")
        return None


def merge_section_into_hosts(original, new_block, logger):
    """将本程序的标记段合并进原 hosts 内容

    自动清理旧标记段（含旧版 fliu2476 格式的 legacy 段），然后把新段追加到文件末尾。
    """
    text = original
    for start_marker, end_marker in [
        (SECTION_START, SECTION_END),
        (LEGACY_SECTION_START, LEGACY_SECTION_END),
    ]:
        while True:
            start = text.find(start_marker)
            if start == -1:
                break
            end = text.find(end_marker)
            if end == -1:
                break
            text = text[:start] + text[end + len(end_marker):]
            logger(f"已清理旧标记段: {start_marker}")
    # 压缩因删除段落留下的多余空行
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.rstrip() + "\n\n" + new_block + "\n"


def write_hosts(content, logger):
    """写入 hosts 文件"""
    try:
        with open(HOSTS_PATH, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        logger("hosts 文件写入成功")
        return True
    except PermissionError:
        logger("错误: 没有权限写入 hosts 文件，请以管理员身份运行")
        return False
    except Exception as e:
        logger(f"写入失败: {e}")
        return False


def flush_dns(logger):
    """刷新 Windows DNS 缓存"""
    commands = [
        ["ipconfig", "/flushdns"],
    ]
    for cmd in commands:
        logger(f"执行: {' '.join(cmd)}")
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, encoding=SYSTEM_ENCODING, timeout=30
            )
            output = (result.stdout or "") + (result.stderr or "")
            for line in output.strip().splitlines():
                if line.strip():
                    logger(f"  {line.strip()}")
            if result.returncode == 0:
                logger("DNS 缓存刷新成功")
            else:
                logger(f"DNS 刷新返回码: {result.returncode}")
        except Exception as e:
            logger(f"DNS 刷新失败: {e}")


class App:
    def __init__(self, root):
        self.root = root
        self.root.title("GitHub Hosts Updater")
        self.root.geometry("640x480")
        self.root.resizable(True, True)

        # 顶部信息
        info_frame = tk.Frame(root, padx=10, pady=8)
        info_frame.pack(fill=tk.X)

        tk.Label(
            info_frame,
            text="GitHub Hosts 自动更新工具",
            font=("Microsoft YaHei", 14, "bold"),
        ).pack(anchor=tk.W)

        tk.Label(
            info_frame,
            text=f"数据源: GitHub520 + fetch-github-hosts + fliu2476/gh-hosts  |  hosts 路径: {HOSTS_PATH}",
            font=("Microsoft YaHei", 9),
            fg="#666",
        ).pack(anchor=tk.W, pady=(2, 0))

        # 管理员状态指示
        self.admin_label = tk.Label(info_frame, text="", font=("Microsoft YaHei", 9))
        self.admin_label.pack(anchor=tk.W, pady=(4, 0))
        self.update_admin_status()

        # 按钮区
        btn_frame = tk.Frame(root, padx=10, pady=4)
        btn_frame.pack(fill=tk.X)

        self.update_btn = tk.Button(
            btn_frame,
            text="立即更新 hosts 并刷新 DNS",
            font=("Microsoft YaHei", 11, "bold"),
            bg="#2d8cf0",
            fg="white",
            activebackground="#1a7ae0",
            activeforeground="white",
            relief=tk.FLAT,
            padx=20,
            pady=8,
            command=self.start_update,
            cursor="hand2",
        )
        self.update_btn.pack(side=tk.LEFT)

        self.restore_btn = tk.Button(
            btn_frame,
            text="恢复上次备份",
            font=("Microsoft YaHei", 10),
            relief=tk.FLAT,
            padx=14,
            pady=8,
            command=self.restore_backup,
            cursor="hand2",
        )
        self.restore_btn.pack(side=tk.LEFT, padx=(8, 0))

        self.open_hosts_btn = tk.Button(
            btn_frame,
            text="打开 hosts 文件",
            font=("Microsoft YaHei", 10),
            relief=tk.FLAT,
            padx=14,
            pady=8,
            command=self.open_hosts_file,
            cursor="hand2",
        )
        self.open_hosts_btn.pack(side=tk.LEFT, padx=(8, 0))

        # IP 优选测速开关
        self.speedtest_var = tk.BooleanVar(value=True)
        self.speedtest_cb = tk.Checkbutton(
            root,
            text="更新时启用 IP 优选测速（对候选 IP 的 443 端口测延迟，自动选最快 IP）",
            variable=self.speedtest_var,
            font=("Microsoft YaHei", 9),
            anchor=tk.W,
        )
        self.speedtest_cb.pack(fill=tk.X, padx=14, pady=(0, 2))

        # 日志区
        log_frame = tk.Frame(root, padx=10, pady=8)
        log_frame.pack(fill=tk.BOTH, expand=True)

        tk.Label(log_frame, text="运行日志:", font=("Microsoft YaHei", 10)).pack(anchor=tk.W)

        self.log_text = scrolledtext.ScrolledText(
            log_frame,
            font=("Consolas", 10),
            wrap=tk.WORD,
            bg="#1e1e1e",
            fg="#d4d4d4",
            insertbackground="white",
            state=tk.DISABLED,
        )
        self.log_text.pack(fill=tk.BOTH, expand=True, pady=(4, 0))

        # 底部状态栏
        self.status_var = tk.StringVar(value="就绪")
        status_bar = tk.Label(
            root,
            textvariable=self.status_var,
            anchor=tk.W,
            font=("Microsoft YaHei", 9),
            fg="#888",
            padx=10,
            pady=4,
            relief=tk.SUNKEN,
        )
        status_bar.pack(fill=tk.X, side=tk.BOTTOM)

        self.logger("程序已启动。点击上方按钮开始更新。")
        self.logger(f"备份目录: {BACKUP_DIR}")

    def update_admin_status(self):
        if is_admin():
            self.admin_label.config(text="✓ 当前已以管理员身份运行", fg="#2ecc71")
        else:
            self.admin_label.config(
                text="⚠ 未以管理员身份运行，更新 hosts 将失败。请右键以管理员身份运行，或点击更新按钮自动提权。",
                fg="#e74c3c",
            )

    def log(self, msg):
        """线程安全的日志输出"""
        timestamp = datetime.datetime.now().strftime("%H:%M:%S")
        line = f"[{timestamp}] {msg}\n"

        def append():
            self.log_text.config(state=tk.NORMAL)
            self.log_text.insert(tk.END, line)
            self.log_text.see(tk.END)
            self.log_text.config(state=tk.DISABLED)

        self.root.after(0, append)
        write_log_to_file(msg)

    def logger(self, msg):
        """供后台线程调用的日志函数"""
        self.log(msg)

    def set_status(self, msg):
        self.root.after(0, lambda: self.status_var.set(msg))

    def set_button_state(self, enabled):
        state = tk.NORMAL if enabled else tk.DISABLED
        self.root.after(0, lambda: self.update_btn.config(state=state))

    def start_update(self):
        """启动更新流程（在后台线程中执行）"""
        # 如果不是管理员，尝试提权重启
        if not is_admin():
            self.logger("检测到非管理员权限，正在请求提权...")
            try:
                run_as_admin()
                self.root.after(500, self.root.destroy)
                return
            except RuntimeError as e:
                self.logger(str(e))
                messagebox.showerror("权限不足", "需要管理员权限才能修改 hosts 文件。\n请右键程序，选择'以管理员身份运行'。")
                return

        self.set_button_state(False)
        speed_enabled = self.speedtest_var.get()
        self.set_status("正在更新...")
        thread = threading.Thread(
            target=self._do_update, args=(speed_enabled,), daemon=True
        )
        thread.start()

    def _do_update(self, speed_enabled):
        """实际更新逻辑"""
        try:
            self.logger("========== 开始更新 ==========")

            # 1. 多源并发下载
            contents = download_all_sources(self.logger)
            if not contents:
                self.logger("错误: 所有数据源均下载失败，请检查网络连接")
                self.set_status("更新失败: 下载失败")
                return

            # 2. 解析所有源的 domain -> 候选 IP 列表
            candidates = parse_hosts_entries(contents, self.logger)
            if not candidates:
                self.logger("错误: 未能从下载数据中解析出任何 hosts 条目")
                self.set_status("更新失败: 数据解析失败")
                return

            # 3. IP 优选测速
            self.logger("---------- IP 优选 ----------")
            entries = select_best_ips(candidates, speed_enabled, self.logger)

            # 4. 备份原 hosts
            original = backup_hosts(self.logger)
            if original is None:
                self.logger("警告: 备份失败，继续更新...")
                try:
                    with open(HOSTS_PATH, "r", encoding="utf-8", errors="ignore") as f:
                        original = f.read()
                except Exception as e:
                    self.logger(f"读取原 hosts 失败: {e}")
                    self.set_status("更新失败: 无法读取 hosts")
                    return

            # 5. 合并（自动清理旧标记段，含旧版格式）
            section = build_section(entries)
            merged = merge_section_into_hosts(original, section, self.logger)

            # 6. 写入
            if not write_hosts(merged, self.logger):
                self.set_status("更新失败: 写入错误")
                return

            # 7. 刷新 DNS
            self.logger("---------- 刷新 DNS 缓存 ----------")
            flush_dns(self.logger)

            self.logger("========== 更新完成 ==========")
            self.set_status("更新完成 ✓")
            self.root.after(0, lambda: messagebox.showinfo("完成", "hosts 文件已更新（含 IP 优选结果），DNS 缓存已刷新！"))

        except Exception as e:
            self.logger(f"发生未预期的错误: {e}")
            self.set_status("更新失败")
        finally:
            self.set_button_state(True)

    def restore_backup(self):
        """恢复最近一次备份"""
        if not is_admin():
            messagebox.showwarning("权限不足", "恢复 hosts 需要管理员权限，请以管理员身份运行。")
            return

        if not os.path.exists(BACKUP_DIR):
            messagebox.showinfo("无备份", "未找到任何备份文件。")
            return

        backups = sorted(
            [f for f in os.listdir(BACKUP_DIR) if f.endswith(".bak")],
            reverse=True,
        )
        if not backups:
            messagebox.showinfo("无备份", "未找到任何备份文件。")
            return

        latest = os.path.join(BACKUP_DIR, backups[0])
        if not messagebox.askyesno("确认恢复", f"是否用以下备份覆盖当前 hosts？\n\n{latest}"):
            return

        try:
            with open(latest, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            with open(HOSTS_PATH, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
            self.logger(f"已从备份恢复: {latest}")
            flush_dns(self.logger)
            messagebox.showinfo("完成", "hosts 已恢复，DNS 缓存已刷新。")
        except Exception as e:
            messagebox.showerror("恢复失败", str(e))

    def open_hosts_file(self):
        """用记事本打开 hosts 文件"""
        try:
            os.startfile(HOSTS_PATH)
        except Exception as e:
            messagebox.showerror("打开失败", str(e))


def run_silent():
    """静默模式：无 GUI，直接执行更新并刷新 DNS（用于任务计划程序）

    可选参数 --no-speedtest：跳过 IP 优选测速，直接使用最高优先级源的数据
    """
    speed_enabled = "--no-speedtest" not in sys.argv

    def log(msg):
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        formatted = f"[{timestamp}] {msg}"
        print(formatted, flush=True)
        write_log_to_file(msg)

    if not is_admin():
        log("错误: 静默模式需要管理员权限，请以管理员身份运行")
        sys.exit(1)

    log("========== 静默模式开始更新 ==========")

    # 多源下载
    contents = download_all_sources(log)
    if not contents:
        log("错误: 所有数据源均下载失败")
        sys.exit(1)

    # 解析候选 IP
    candidates = parse_hosts_entries(contents, log)
    if not candidates:
        log("错误: 未能从下载数据中解析出任何 hosts 条目")
        sys.exit(1)

    # IP 优选
    log("---------- IP 优选 ----------")
    entries = select_best_ips(candidates, speed_enabled, log)

    # 备份
    original = backup_hosts(log)
    if original is None:
        try:
            with open(HOSTS_PATH, "r", encoding="utf-8", errors="ignore") as f:
                original = f.read()
        except Exception as e:
            log(f"读取原 hosts 失败: {e}")
            sys.exit(1)

    # 合并（自动清理旧标记段，含旧版格式）
    section = build_section(entries)
    merged = merge_section_into_hosts(original, section, log)

    # 写入
    if not write_hosts(merged, log):
        sys.exit(1)

    # 刷新 DNS
    log("---------- 刷新 DNS 缓存 ----------")
    flush_dns(log)

    log("========== 更新完成 ==========")
    sys.exit(0)


def main():
    # 静默模式（用于任务计划程序自动更新）
    if "--silent" in sys.argv:
        run_silent()
        return

    root = tk.Tk()
    try:
        # 设置 DPI 感知（Windows 8.1+）
        ctypes.windll.shcore.SetProcessDpiAwareness(1)
    except Exception:
        pass
    app = App(root)
    root.mainloop()


if __name__ == "__main__":
    main()
